//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::exercise::Entity as Exercise;
pub use super::person::Entity as Person;
pub use super::timeslot::Entity as Timeslot;
pub use super::work_set::Entity as WorkSet;
